version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "8080:8080"
    networks:
      - ecommerce-store-network
    env_file:
      - ./server/.env

  frontend:
    build: ./client
    ports:
      - "5173:5173"
    networks:
      - ecommerce-store-network
    env_file:
      - ./client/.env

networks:
  ecommerce-store-network:
    driver: bridge
